using LgymApi.Application.Common.Errors;
using LgymApi.Application.Common.Results;
using LgymApi.Application.WorkoutProgress.ProgressData.Models;
using LgymApi.Domain.Enums;
using LgymApi.Domain.ValueObjects;
using LgymApi.Resources;
using MeasurementEntity = LgymApi.Domain.Entities.Measurement;

namespace LgymApi.Application.WorkoutProgress.ProgressData;

public sealed partial class WorkoutProgressReadWriteService
{
    public Task<Result<Unit, AppError>> AddMeasurementAsync(Id<LgymApi.Domain.Entities.User> currentUserId, BodyParts bodyPart, MeasurementUnits unit, double value, CancellationToken cancellationToken = default) => AddMeasurementsAsync(currentUserId, [new MeasurementWriteModel(bodyPart, unit, value)], cancellationToken);
    public async Task<Result<Unit, AppError>> AddMeasurementsAsync(Id<LgymApi.Domain.Entities.User> userId, IReadOnlyCollection<MeasurementWriteModel> values, CancellationToken token = default)
    {
        if (userId.IsEmpty) return Result<Unit, AppError>.Failure(new InvalidMeasurementError(Messages.InvalidId));
        if (values.Count == 0 || values.Any(x => !Features.Measurements.MeasurementUnitResolver.IsUnitAllowedForBodyPart(x.BodyPart, x.Unit) || x.Value <= 0)) return Result<Unit, AppError>.Failure(new InvalidMeasurementError(Messages.FieldRequired));
        foreach (var x in values) await _dependencies.MeasurementRepository.AddAsync(new MeasurementEntity { Id = Id<MeasurementEntity>.New(), UserId = userId, BodyPart = x.BodyPart, Unit = x.Unit.ToString(), Value = x.Value }, token);
        await _dependencies.UnitOfWork.SaveChangesAsync(token); return Result<Unit, AppError>.Success(Unit.Value);
    }
    public async Task<Result<MeasurementReadModel, AppError>> GetMeasurementDetailAsync(Id<LgymApi.Domain.Entities.User> current, Id<MeasurementEntity> id, CancellationToken token = default)
    { if (current.IsEmpty || id.IsEmpty) return Result<MeasurementReadModel, AppError>.Failure(new InvalidMeasurementError(Messages.InvalidId)); var item = await _dependencies.MeasurementRepository.FindByIdAsync(id, token); return item == null ? Result<MeasurementReadModel, AppError>.Failure(new MeasurementNotFoundError(Messages.DidntFind)) : current != item.UserId ? Result<MeasurementReadModel, AppError>.Failure(new MeasurementForbiddenError(Messages.Forbidden)) : Result<MeasurementReadModel, AppError>.Success(MapMeasurement(item)); }
    public async Task<Result<MeasurementReadModel, AppError>> GetMeasurementDetailForOwnerAsync(Id<LgymApi.Domain.Entities.User> owner, Id<MeasurementEntity> id, CancellationToken token = default)
    { if (owner.IsEmpty || id.IsEmpty) return Result<MeasurementReadModel, AppError>.Failure(new InvalidMeasurementError(Messages.InvalidId)); var item = await _dependencies.MeasurementRepository.FindByIdAsync(id, token); return item == null || item.UserId != owner ? Result<MeasurementReadModel, AppError>.Failure(new MeasurementNotFoundError(Messages.DidntFind)) : Result<MeasurementReadModel, AppError>.Success(MapMeasurement(item)); }
    public async Task<Result<Id<LgymApi.Domain.Entities.User>, AppError>> GetMeasurementOwnerAsync(Id<MeasurementEntity> id, CancellationToken token = default)
    { var item = await _dependencies.MeasurementRepository.FindByIdAsync(id, token); return item == null ? Result<Id<LgymApi.Domain.Entities.User>, AppError>.Failure(new MeasurementNotFoundError(Messages.DidntFind)) : Result<Id<LgymApi.Domain.Entities.User>, AppError>.Success(item.UserId); }
    public Task<Result<List<MeasurementReadModel>, AppError>> GetMeasurementsListForOwnerAsync(Id<LgymApi.Domain.Entities.User> id, BodyParts? body, MeasurementUnits? unit, CancellationToken token = default) => GetMeasurementsAsync(id,id,body,unit,false,token);
    public Task<Result<List<MeasurementReadModel>, AppError>> GetMeasurementsHistoryForOwnerAsync(Id<LgymApi.Domain.Entities.User> id, BodyParts? body, MeasurementUnits? unit, CancellationToken token = default) => GetMeasurementsAsync(id,id,body,unit,true,token);
    public Task<Result<List<MeasurementReadModel>, AppError>> GetMeasurementsListAsync(Id<LgymApi.Domain.Entities.User> current, Id<LgymApi.Domain.Entities.User> route, BodyParts? body, MeasurementUnits? unit, CancellationToken token = default) => GetMeasurementsAsync(current,route,body,unit,false,token);
    public Task<Result<List<MeasurementReadModel>, AppError>> GetMeasurementsHistoryAsync(Id<LgymApi.Domain.Entities.User> current, Id<LgymApi.Domain.Entities.User> route, BodyParts? body, MeasurementUnits? unit, CancellationToken token = default) => GetMeasurementsAsync(current,route,body,unit,true,token);
    public Task<Result<MeasurementTrendReadModel, AppError>> GetMeasurementsTrendForOwnerAsync(Id<LgymApi.Domain.Entities.User> id, BodyParts body, MeasurementUnits unit, CancellationToken token = default) => GetMeasurementsTrendAsync(id,id,body,unit,token);
    public Task<Result<List<MeasurementTrendReadModel>, AppError>> GetMeasurementsTrendsForOwnerAsync(Id<LgymApi.Domain.Entities.User> id, CancellationToken token = default) => GetMeasurementsTrendsAsync(id,id,token);
    public async Task<Result<MeasurementTrendReadModel, AppError>> GetMeasurementsTrendAsync(Id<LgymApi.Domain.Entities.User> current, Id<LgymApi.Domain.Entities.User> route, BodyParts body, MeasurementUnits unit, CancellationToken token = default) { if (current.IsEmpty || current != route) return Result<MeasurementTrendReadModel, AppError>.Failure(new MeasurementForbiddenError(Messages.Forbidden)); var all=await _dependencies.MeasurementRepository.GetByUserAsync(route,body,token); return Result<MeasurementTrendReadModel,AppError>.Success(BuildTrend(all.OrderBy(x=>x.CreatedAt).ToList(),body,unit)); }
    public async Task<Result<List<MeasurementTrendReadModel>, AppError>> GetMeasurementsTrendsAsync(Id<LgymApi.Domain.Entities.User> current, Id<LgymApi.Domain.Entities.User> route, CancellationToken token = default) { if(current.IsEmpty||current!=route)return Result<List<MeasurementTrendReadModel>,AppError>.Failure(new MeasurementForbiddenError(Messages.Forbidden)); var all=await _dependencies.MeasurementRepository.GetByUserAsync(route,null,token); return Result<List<MeasurementTrendReadModel>,AppError>.Success(all.GroupBy(x=>x.BodyPart).OrderBy(x=>x.Key.ToString()).Select(x=>BuildTrend(x.OrderBy(y=>y.CreatedAt).ToList(),x.Key,ParseUnit(x.Last().Unit))).ToList()); }
    private async Task<Result<List<MeasurementReadModel>,AppError>> GetMeasurementsAsync(Id<LgymApi.Domain.Entities.User> current,Id<LgymApi.Domain.Entities.User> route,BodyParts? body,MeasurementUnits? unit,bool asc,CancellationToken token){if(current.IsEmpty||current!=route)return Result<List<MeasurementReadModel>,AppError>.Failure(new MeasurementForbiddenError(Messages.Forbidden));var all=await _dependencies.MeasurementRepository.GetByUserAsync(route,body,token);if(all.Count==0)return Result<List<MeasurementReadModel>,AppError>.Failure(new MeasurementNotFoundError(Messages.DidntFind));return Result<List<MeasurementReadModel>,AppError>.Success((asc?all.OrderBy(x=>x.CreatedAt):all.OrderByDescending(x=>x.CreatedAt)).Select(x=>MapMeasurement(x,unit??ParseUnit(x.Unit))).ToList());}
    private static MeasurementUnits ParseUnit(string? value)=>Features.Measurements.MeasurementUnitResolver.TryParseStoredUnit(value,out var unit)?unit:MeasurementUnits.Unknown;
    private MeasurementReadModel MapMeasurement(MeasurementEntity x,MeasurementUnits? target=null){var from=ParseUnit(x.Unit);var to=target??from;var value=from==to?x.Value:Features.Measurements.MeasurementUnitResolver.IsWeightMeasurement(x.BodyPart)&&Features.Measurements.MeasurementUnitResolver.TryGetWeightUnit(from,out var fw)&&Features.Measurements.MeasurementUnitResolver.TryGetWeightUnit(to,out var tw)?_dependencies.WeightUnitConverter.Convert(x.Value,fw,tw):Features.Measurements.MeasurementUnitResolver.IsLengthMeasurement(x.BodyPart)&&Features.Measurements.MeasurementUnitResolver.TryGetHeightUnit(from,out var fh)&&Features.Measurements.MeasurementUnitResolver.TryGetHeightUnit(to,out var th)?_dependencies.HeightUnitConverter.Convert(x.Value,fh,th):x.Value;return new(x.Id,x.UserId,x.BodyPart,to,Math.Round(value,2),x.CreatedAt,x.UpdatedAt);}
    private static MeasurementTrendReadModel BuildTrend(IReadOnlyList<MeasurementEntity> x,BodyParts body,MeasurementUnits unit){if(x.Count==0)return new(body,unit,null,null,null,null,null,null,null,null,null,"insufficient_data",0);var first=Math.Round(x[0].Value,2);var last=Math.Round(x[^1].Value,2);var change=Math.Round(last-first,2);return new(body,unit,first,last,change,Math.Abs(first)<=.0001?0:Math.Round(change/first*100,2),first,x[0].CreatedAt,last,x[^1].CreatedAt,Math.Abs(change),x.Count==1?"insufficient_data":change>0.0001?"up":change<-.0001?"down":"same",x.Count);}
}
