using System.Collections.Immutable;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace LgymApi.Resources.Generator;

[Generator]
public sealed class EmailsResxGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor ResxParseFailed = new(
        id: "LGYMRES005",
        title: "Failed to parse Emails.resx",
        messageFormat: "Failed to parse Emails.resx at '{0}': {1}",
        category: "Resources",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ResxNoKeys = new(
        id: "LGYMRES006",
        title: "No resource keys found",
        messageFormat: "No resource keys found in Emails.resx at '{0}'.",
        category: "Resources",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resxFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("Emails.resx", StringComparison.OrdinalIgnoreCase));

        var resxContent = resxFiles.Select((file, cancellationToken) =>
        {
            var text = file.GetText(cancellationToken)?.ToString() ?? string.Empty;
            return (Path: file.Path, Content: text);
        });

        context.RegisterSourceOutput(resxContent, static (context, input) =>
        {
            if (string.IsNullOrWhiteSpace(input.Content))
            {
                context.ReportDiagnostic(Diagnostic.Create(ResxNoKeys, Location.None, input.Path));
                context.AddSource("Emails.g.cs", GenerateSource(ImmutableArray<string>.Empty));
                return;
            }

            var (keys, error) = ReadKeys(input.Content);
            if (!string.IsNullOrWhiteSpace(error))
            {
                context.ReportDiagnostic(Diagnostic.Create(ResxParseFailed, Location.None, input.Path, error));
            }

            if (keys.Length == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(ResxNoKeys, Location.None, input.Path));
            }

            context.AddSource("Emails.g.cs", GenerateSource(keys));
        });
    }

    private static (ImmutableArray<string> Keys, string? Error) ReadKeys(string content)
    {
        try
        {
            var document = XDocument.Parse(content);
            var keys = document.Root?
                .Elements("data")
                .Select(element => element.Attribute("name")?.Value)
                .Where(value => !string.IsNullOrWhiteSpace(value))
                .Select(value => value!)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(value => value, StringComparer.Ordinal)
                .ToImmutableArray();

            return (keys ?? ImmutableArray<string>.Empty, null);
        }
        catch (Exception ex)
        {
            return (ImmutableArray<string>.Empty, ex.Message);
        }
    }

    private static string GenerateSource(ImmutableArray<string> keys)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Resources;");
        builder.AppendLine();
        builder.AppendLine("namespace LgymApi.Resources;");
        builder.AppendLine();
        builder.AppendLine("public static class Emails");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly ResourceManager ResourceManager = new ResourceManager(\"LgymApi.Resources.Resources.Emails\", typeof(Emails).Assembly);");
        builder.AppendLine();

        foreach (var key in keys)
        {
            var propertyName = MakeIdentifier(key);
            builder.AppendLine($"    public static string {propertyName} => ResourceManager.GetString(\"{key}\", CultureInfo.CurrentUICulture) ?? \"{key}\";");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string MakeIdentifier(string key)
    {
        if (SyntaxFacts.IsValidIdentifier(key))
        {
            return key;
        }

        var builder = new StringBuilder(key.Length + 1);
        if (key.Length == 0 || !SyntaxFacts.IsIdentifierStartCharacter(key[0]))
        {
            builder.Append('_');
        }

        foreach (var ch in key)
        {
            builder.Append(SyntaxFacts.IsIdentifierPartCharacter(ch) ? ch : '_');
        }

        var candidate = builder.ToString();
        return SyntaxFacts.IsValidIdentifier(candidate) ? candidate : "_" + candidate;
    }
}
