using System.Collections.Immutable;
using System.Text;
using System.IO;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace LgymApi.Resources.Generator;

[Generator]
public sealed class MessagesResxGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resxFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("Messages.resx", StringComparison.OrdinalIgnoreCase));

        var resxContent = resxFiles.Select((file, cancellationToken) =>
        {
            var text = file.GetText(cancellationToken)?.ToString() ?? string.Empty;
            return (Path: file.Path, Content: text);
        });

        context.RegisterSourceOutput(resxContent, static (context, input) =>
        {
            if (string.IsNullOrWhiteSpace(input.Content))
            {
                return;
            }

            var keys = ReadKeys(input.Content);
            if (keys.Length == 0)
            {
                return;
            }

            var source = GenerateSource(keys);
            context.AddSource("Messages.g.cs", source);
        });
    }

    private static ImmutableArray<string> ReadKeys(string content)
    {
        try
        {
            var document = XDocument.Parse(content);
            var keys = document.Root?
                .Elements("data")
                .Select(element => element.Attribute("name")?.Value)
                .Where(value => !string.IsNullOrWhiteSpace(value))
                .Select(value => value!)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(value => value, StringComparer.Ordinal)
                .ToImmutableArray();

            return keys ?? ImmutableArray<string>.Empty;
        }
        catch
        {
            return ImmutableArray<string>.Empty;
        }
    }

    private static string GenerateSource(ImmutableArray<string> keys)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Resources;");
        builder.AppendLine();
        builder.AppendLine("namespace LgymApi.Resources;");
        builder.AppendLine();
        builder.AppendLine("public static class Messages");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly ResourceManager ResourceManager = new ResourceManager(\"LgymApi.Resources.Resources.Messages\", typeof(Messages).Assembly);");
        builder.AppendLine();

        foreach (var key in keys)
        {
            var propertyName = MakeIdentifier(key);
            builder.AppendLine($"    public static string {propertyName} => ResourceManager.GetString(\"{key}\", CultureInfo.CurrentUICulture) ?? \"{key}\";");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string MakeIdentifier(string key)
    {
        if (SyntaxFacts.IsValidIdentifier(key))
        {
            return key;
        }

        var builder = new StringBuilder(key.Length + 1);
        if (key.Length == 0 || !SyntaxFacts.IsIdentifierStartCharacter(key[0]))
        {
            builder.Append('_');
        }

        foreach (var ch in key)
        {
            builder.Append(SyntaxFacts.IsIdentifierPartCharacter(ch) ? ch : '_');
        }

        var candidate = builder.ToString();
        return SyntaxFacts.IsValidIdentifier(candidate) ? candidate : "_" + candidate;
    }
}
