// <auto-generated />
using LgymApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LgymApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602193000_AddTrainerFeedbackToReportSubmissions")]
    partial class AddTrainerFeedbackToReportSubmissions
    {
    }
}
